name: Deploy Backend and Frontend

on:
  workflow_dispatch:  # Enables manual trigger for the workflow
  push:
    branches:
      - main
    paths: 
      - 'back/**'
      - 'front/**'

jobs:
  dockerize-backend:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' && (contains(github.event.head_commit.message, 'back/') || contains(github.event.head_commit.message, 'front/')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: List directory contents
        run: ls -R

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.4.1
        with:
          context: back/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/team-25:latest

  deploy-backend:
    needs: dockerize-backend
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' && (contains(github.event.head_commit.message, 'back/') || contains(github.event.head_commit.message, 'front/')) }}
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/team-25:latest

      - name: Run docker container
        run: sudo systemctl restart backend.service

  deploy-frontend:
    needs: dockerize-backend
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' && (contains(github.event.head_commit.message, 'back/') || contains(github.event.head_commit.message, 'front/')) }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.12.1

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: |
            frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: List directory contents
        run: ls -R

      - name: Install dependencies
        run: |
          cd ./front
          npm install

      - name: Build the frontend
        run: |
          cd ./front
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./front/docs/ s3://${{ secrets.AWS_S3_BUCKET }} --region ${{ secrets.AWS_REGION }} --delete
